[package]
name = "tarir"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.9.0"
base64 = "0.22.1"
byteorder = "1.5.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
tera = "1.20.0"

[profile.release]
lto = true
strip = true
opt-level = 3

