[package]
name = "tarir"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = true
strip = true
opt-level = 3

[dependencies]
actix-web = "4.9.0"
base64 = "0.22.1"
byteorder = "1.5.0"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
tera = "1.20.0"

